### ISSUE TITLE
volume-data-source-validator container image should be published for testing

### ISSUE THREAD

**Issue by mkimuram** [kubernetes-csi/volume-data-source-validator#22]
volume-data-source-validator image is used for E2E tests in k/k, therefore it should be published.

**Comment by mkimuram** [comment]
@bswartz  There is no document clearly describing this, but it seems that `k8s.gcr.io/sig-storage/volume-data-source-validator:v0.1.0` is already available. Do documents need to be updated?

**Comment by maya-r** [comment]
It's also referenced in [the following blog post](https://kubernetes.io/blog/2021/08/30/volume-populators-redesigned/). following along with it doesn't work as expected when the image isn't public

**Comment by mkimuram** [comment]
I think that it would be OK to wait for beta to update. However, for users who would like to test this feature as an alpha feature, it would be still helpful to update the [yaml](https://github.com/kubernetes-csi/volume-data-source-validator/blob/master/deploy/kubernetes/setup-data-source-validator.yaml#L29) to use `sig-storage/volume-data-source-validator:v0.1.0` (and hopefully also update README).
